spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Swallows?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      #单个数据的大小
      max-file-size: 1MB
      #文件上传是否开启
      enabled: true
      #总数据的大小
      max-request-size: 10MB
#  thymeleaf清除缓存，否则修改只有等重启之后才生效
#  thymeleaf:
#    cache=false:#  messages:

#    basename: i18n/messages

server:
  port: 8080

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log
