spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Swallows?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=CST
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log
